apiVersion: v1
kind: Secret
metadata:
  name: retrieval-hub-pg
  namespace: retrieval-hub
type: Opaque
stringData:
  POSTGRES_USER: retrievalhub
  POSTGRES_PASSWORD: retrievalhub
  POSTGRES_DB: retrievalhub
  VECTORS_DB: retrievalhub_vectors
