apiVersion: v1
kind: Secret
metadata:
  name: retrieval-hub-pg
  namespace: retrieval-hub
type: Opaque
stringData:
  POSTGRES_USER: retrievalhub
  POSTGRES_PASSWORD: retrievalhub
  POSTGRES_DB: retrievalhub
  VECTORS_DB: retrievalhub_vectors
  RETRIEVAL_HUB_DB_URL: "postgresql+psycopg://retrievalhub:retrievalhub@retrieval-hub-pg:5432/retrievalhub"
  RETRIEVAL_HUB_VECTORS_DB_URL: "postgresql+psycopg://retrievalhub:retrievalhub@retrieval-hub-pg:5432/retrievalhub_vectors"
