modules:
  - module_type: llama_index_chunk
    chunk_method:
      - Token
      - Sentence
    chunk_size:
      - 256
      - 512
      - 1024
    chunk_overlap:
      - 0
      - 64
    add_file_name: en
