apiVersion: v1
kind: Service
metadata:
  name: retrieval-hub-ui
  labels:
    app.kubernetes.io/name: retrieval-hub-ui
    app.kubernetes.io/part-of: retrieval-hub
    app.kubernetes.io/component: ui
spec:
  selector:
    app.kubernetes.io/name: retrieval-hub-ui
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
